# Generated by Django 4.0.6 on 2022-07-12 09:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_user_id_auctionlisting_auctioncomments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
