# Generated by Django 4.0.6 on 2022-07-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_alter_auctionlisting_category_delete_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(blank=True, choices=[('Other', 'Other'), ('2', 'TV'), ('3', 'Laptop'), ('4', 'Smartphone'), ('5', 'Tablet')], max_length=50),
        ),
    ]
