# Generated by Django 4.0.6 on 2022-07-17 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_alter_auctionlisting_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='category',
        ),
    ]
