# Generated by Django 4.0.6 on 2022-07-17 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0031_alter_auctionlisting_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionbids',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_item', to='auctions.auctionlisting'),
        ),
        migrations.AddField(
            model_name='auctioncomments',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_item', to='auctions.auctionlisting'),
        ),
    ]
