# Generated by Django 4.0.6 on 2022-07-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0032_auctionbids_item_auctioncomments_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionbids',
            name='amount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
