# Generated by Django 4.0.6 on 2022-07-18 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0033_auctionbids_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctioncomments',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 18, 20, 12, 40, 529915)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auctionbids',
            name='amount',
            field=models.FloatField(verbose_name=''),
        ),
    ]
