# Generated by Django 4.0.6 on 2022-07-19 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0034_auctioncomments_time_alter_auctionbids_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctioncomments',
            name='comment',
            field=models.CharField(max_length=1000, verbose_name=''),
        ),
        migrations.CreateModel(
            name='ClosedAuctions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='winning_item', to='auctions.auctionlisting')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='winning_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
