# Generated by Django 4.0.6 on 2022-07-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0039_alter_auctionbids_user_alter_auctioncomments_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionbids',
            name='amount',
            field=models.FloatField(),
        ),
    ]
